### ISSUE TITLE
Deployement of the Doxygen documentation on a web server

### ISSUE THREAD

**Issue by COLAMAroro** [Sangliers-Feroces/Zia-Docs#1]
Bonjour

Est-il possible d'avoir la documentation Doxygen compilée et déployée sur un serveur web ?

Il est probablement possible de le faire via une [Action GitHub](https://github.com/mattnotmitt/doxygen-action), et déployer via les [GitHub Pages](https://github.com/peaceiris/actions-gh-pages)

**Comment by COLAMAroro** [comment]
In english

--

Hello

Is is possible to get the Doxygen configuration compiled and deployed on a web server for easy browsing ?

It can probably be done with [GitHub Actions](https://github.com/mattnotmitt/doxygen-action) and deployed via [GitHub Pages](https://github.com/peaceiris/actions-gh-pages)

**Comment by adrien-lenglet** [comment]
Sure thing. Please make a PR for that and we'll make that happen !

**Comment by COLAMAroro** [comment]
As you know, it is not my reponsability to maintain the API.

I recommended the uses of GitHub Actions and Pages to have it done automatically, but if you prefer to upload a compiled documentation by hand and every update, still works for me :)

**Comment by adrien-lenglet** [comment]
I appreciate the recommendation and I think this will have a positive impact on the project. However, I personally am not willing to put the time to develop and test this feature. I offer you to take care of that, and open a PR once you're happy with your integration. If you encounter any permission-related limitation, hit me up and we'll find a solution.

Having built files on the repo isn't a currently considered option. Please make sure the build doesn't push anything redundant on the repo so your PR is successful.
