### ISSUE TITLE
API is Incompatible with Visual Studio 2019

### ISSUE THREAD

**Issue by COLAMAroro** [Sangliers-Feroces/Zia-Docs#2]
Hello

I've tried to make a dummy module using Visual Studio 2019 (Version 16.8.2, with Visual C++ 2019), but the API can not be compiled, using this snippet

```cpp
#include "include/zia/Zia.hpp"
#include "include/zia/module/Parser.hpp"
#include "include/zia/module/ConnectionWrapper.hpp"
#include "include/zia/module/Handler.hpp"
#include "include/zia/module/Logger.hpp"
#include <stdexcept>

class test : public Zia::Module::IParser
{
public:
	test() = default;
	std::unique_ptr<IInstance> create(Zia::IInput& input, Zia::ILogger& log, Zia::IRequest::IEmitter& requestEmitter) { throw std::logic_error("Not implemented"); };
};

std::unique_ptr<Zia::Module::IParser> createParser(Zia::IConf& conf)
{
	conf = conf;
	return std::make_unique<test>();
}
```

There is the list of errors:

![https://i.imgur.com/Hi0Uk0J.png](https://i.imgur.com/Hi0Uk0J.png "List of errors")

(This code compiles without issues on G++)

**Comment by adrien-lenglet** [comment]
Thanks for the feedback !
I do not have a running copy of Visual Studio at the moment so I can't reproduce.
Have you found any workaround for that problem, that still would be G++/clang compliant  ?

**Comment by COLAMAroro** [comment]
I have not yet looked for a fix or a workaround, but working around C++ types in a `export "C"` will probably break things anyway

You could probably get a Visual Studio installation and Licence using [Azure Dev Tools for Teaching](https://azureforeducation.microsoft.com/devtools)

**Comment by adrien-lenglet** [comment]
Ok so you would recommend not to wrap any symbol in an `export "C"` ? I'm a bit worried about C++ name mangling making manual shared lib opening tedious. For example, `createLogger` becomes `_Z12createLoggerRN3Zia5IConfE` using C++ linkage instead of C linkage. A solution keeping C symbol mangling across all platforms would be much appreciated.

I read on Microsoft doc that `__declspec( dllimport )` should be prepend to DLL prototypes.
https://docs.microsoft.com/fr-fr/cpp/build/exporting-c-functions-for-use-in-c-or-cpp-language-executables?view=msvc-160
Does that fix the problem for you ?

Thanks for the advice to install Visual Studio. However, I'm not planning to use that software anytime soon. Would be glad to solve this issue on your end.

**Comment by COLAMAroro** [comment]
> I read on Microsoft doc that `__declspec( dllimport )` should be prepend to DLL prototypes.
> https://docs.microsoft.com/fr-fr/cpp/build/exporting-c-functions-for-use-in-c-or-cpp-language-executables?view=msvc-160
> Does that fix the problem for you ?

Sadly, it is still broken

![Screenshot](https://i.imgur.com/Yny7lkw.png "Screenshot of the compilation result")

Regarding the mangling, `extern "C"` is obviously required, but it is impossible to move C++ object around. The only visible solution I can think of right now is using raw pointers

**Comment by COLAMAroro** [comment]
Just in case, I've used `__declspec(dllexport)` instead of `__declspec(dllimport)`, as import is used for clients

Reference: [MSDN - Exporting from a DLL Using __declspec(dllexport)](https://docs.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-declspec-dllexport?view=msvc-160)

**Comment by adrien-lenglet** [comment]
Ok thanks for testing with the `dllexport` qualifier. I think this still should be included in the fix. As you said, MSVC ABI seems to stricly forbid returning objects on C linkage.

Converting the `unique_ptr` to a raw pointer looks like a nice solution to me. Implementations should be able to easily wrap that and it surely makes the API less restrictive. Can you please check if #3 works for you ?

**Comment by COLAMAroro** [comment]
After some tests, this indeed fixes the problem, I am able to compile a DLL, and use `LoadLibraryA`. Issue can be closed

**Comment by adrien-lenglet** [comment]
Great news !
Thank you for contributing.
