### ISSUE TITLE
[Question]: variable body in interface

### ISSUE THREAD

**Issue by Sharkigamers** [Sangliers-Feroces/Zia-Docs#4]
Hello,

I would like to know, why in the IResponse and IRequest, your body is a std::vector<char>. Isn't it better to declare it as a std::string ?

Best regards.

**Comment by adrien-lenglet** [comment]
Hello,

It's more of a design choice. `std::string` is best suited for text, where `std::vector<char>` can basically contain anything : text, images, audio, etc. We chose to consider the body as a byte buffer rather that a string. Keep in mind that it is still very simple to insert an `std::string` into a `std::vector<char>` using the `insert` method.

Hope that helps.
